CREATE TABLE [dbo].[UserApp]
(
	[Id] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
	[Email] NVARCHAR(200) NOT NULL,
	[Username] NVARCHAR(50) NOT NULL,
	[Password] VARBINARY(64) NOT NULL,
	[IsAdmin] BIT NOT NULL DEFAULT 0,
	[Salt] NVARCHAR(100) NOT NULL,
	[BirthDate] DATETIME2 NULL, 
    CONSTRAINT PK_UserApp PRIMARY Key([Id]),
	CONSTRAINT UK_Email UNIQUE ([Email])
)
